### ISSUE TITLE
Docker compose error rosrun rviz rviz not found

### ISSUE THREAD

**Issue by Virgile-Dauge** [virgileTN/docker-ros#4]
```
virgile@coucou:~/workspace/VLP16-utilities$ docker-compose up
Creating master
Creating rviz
Attaching to master, rviz
rviz      | /ros_entrypoint.sh: line 6: exec: rosrun rviz rviz: not found
rviz exited with code 127
```
docker-compose.yml : 
```
version: '3'
services:
  master:
    image: virgiletn/docker-ros:kinetic-core
    container_name: master

  rviz:
    image: virgiletn/docker-ros:kinetic-rviz-intel
    container_name: rviz
    depends_on:
      - "master"
    environment:
        - "ROS_HOSTNAME=rviz"
        - "ROS_MASTER_URI=http://master:11311"
        - "DISPLAY"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    command: 
      - rosrun rviz rviz
```
